configMapGenerator:
- files:
  - application.yml
  name: cloud-sample-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: cepg82249961newacr.azurecr.io/82249961new
  newTag: "202411010708"
- name: cepgstapacr.azurecr.io/cloud-sample
  newTag: "202408120727"
