configMapGenerator:
- files:
  - application.yml
  name: 82249961new-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: cepg82249961newacr.azurecr.io/82249961new
  newTag: "202411031400"
