kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv82249961new
spec:
  csi:
    driver: file.csi.azure.com
    volumeHandle: 82249961new
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cepg-aa-std-rwmany
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  volumeMode: Filesystem
