kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prod-cepg-aa-std-pvc
  namespace: '82249961new’
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: cepg-aa-std-rwmany
  volumeMode: Filesystem
