apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cepg-aa-std-rwmany
provisioner: file.csi.azure.com
parameters:
  skuName: Standard_LRS
  location: koreacentral
reclaimPolicy: Retain
mountOptions:
  - dir_mode=0777
  - file_mode=0777
allowVolumeExpansion: true
volumeBindingMode: Immediate
